#!/bin/bash

lxsession &
sxhkd &

compton --config /dev/null --backend glx &
polybar example &
# light-locker &
xiccd &

bspc monitor -d I II III IV V VI VII VIII IX
bspc config window_gap 2
bspc config border_width 2
bspc config normal_border_color '#4c566a'
bspc config active_border_color '#4c566a'
bspc config focused_border_color '#5e81ac'
bspc config presel_feedback_color '#ebcb8b'

bspc rule -a mpv state=floating
bspc rule -a kitty-floating state=floating
bspc rule -a g-speak state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a feh state=floating
bspc rule -a spotify state=pseudo_tiled

bspc config top_padding 40

wallpaper="${HOME}/.local/share/wallpaper"
wallpaper_conf="${wallpaper}.conf"
if [[ -f "${wallpaper}" ]]
then
  kind=$(cat "${wallpaper_conf}" || echo "scale")
  feh --bg-"${kind}" "${wallpaper}" &
fi

if [[ -f "${HOME}/.Xresources" ]]; then
  xrdb -merge "${HOME}/.Xresources"
fi
